api-version: 1.19
main: net.farlands.sanctuary.FarLands
name: FarLands
description: FarLands version 4 - Sanctuary
authors: [xCassyx, Kishiko73, SuperAnimeBoi, funnyboy_roks, Majekdor]
version: 4
depend: [ChestShops, ProtocolLib, RegionProtection, Votifier, CoreProtect]
libraries:
#  - net.dv8tion:JDA:5.0.0-beta.9
  - org.openjdk.nashorn:nashorn-core:15.4
  - com.squareup.moshi:moshi:1.15.0
  - org.jetbrains:annotations:24.0.1
