api-version: 1.19
main: net.farlands.sanctuary.FarLands
name: FarLands
description: FarLands version 4 - Sanctuary
authors: [xCassyx, Kishiko73, SuperAnimeBoi, funnyboy_roks, Majekdor]
version: 4
depend: [ChestShops, ProtocolLib, RegionProtection, Votifier, CoreProtect]
loadbefore: [RegionProtection]
libraries:
  - org.openjdk.nashorn:nashorn-core:15.4
  - com.squareup.moshi:moshi:1.14.0
  - org.jetbrains:annotations:23.1.0