api-version: 1.18
main: net.farlands.sanctuary.FarLands
name: FarLands
description: FarLands version 4 - Sanctuary
authors: [xCassyx, Kishiko73, SuperAnimeBoi, funnyboy_roks, Majekdor]
version: 4
depend: [ChestShops, ProtocolLib, RegionProtection, Votifier, CoreProtect]
loadbefore: [RegionProtection]