api-version: 1.20.6
main: net.farlands.sanctuary.FarLands
name: FarLands
description: FarLands v5 - Expedition
authors:
  - xCassyx
  - Kishiko73
  - SuperAnimeBoi
  - funnyboy_roks
  - Majekdor
version: 5
depend:
  - ChestShops
  - ProtocolLib
  - RegionProtection
  - Votifier
  - CoreProtect
libraries:
  - 'net.dv8tion:JDA:5.0.0-beta.12'
  - 'com.squareup.moshi:moshi:1.15.2'
  - 'org.jetbrains:annotations:26.1.0'
  - 'org.graalvm.sdk:graal-sdk:25.0.3'
  - 'org.graalvm.js:js:23.0.0'
  - 'org.graalvm.js:js-scriptengine:25.0.3'
