api-version: 1.16
main: net.farlands.sanctuary.FarLands
name: FarLands
description: FarLands version 3 - Sanctuary
authors: [xCassyx, Kishiko73, SuperAnimeBoi]
version: 3
depend: [ChestShops, ProtocolLib, RegionProtection, Votifier]